sonar.host.url=https://sonarcloud.io
sonar.projectKey=kitsuiwebster_fake-blue-screen-backend
sonar.organization=kitsuiwebster
sonar.sources=.
sonar.exclusions=**/tests/**,**/__pycache__/**
sonar.python.version=3.12
